name: AllTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
  steps:
    - uses: actions/checkout@v2 #6
    - name: Install fastlane
  run: |
      bundle install #7
    - name: Execute fastlane
      run: |
        bundle exec fastlane scan(scheme: "AllTests", clean: true)